name = "my-portfolio"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[assets]
directory = "./public"

[[d1_databases]]
binding = "DB"
database_name = "portfolio-db"
database_id = "d9e46eaa-6f5f-428c-98e2-b67f4da500ba"

[vars]
ALLOW_REGISTRATION = "true"
INVITE_CODE = "NIKUNJ-2026"
JWT_SECRET_KEY = "your-very-secret-key"
